# Generated by Django 4.2 on 2024-04-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataAvailability', '0001_initial'),
        ('SportingBuddiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavailabilities',
            name='profiles_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportingBuddiesApp.profiles'),
        ),
        migrations.AddField(
            model_name='courtavailabilities',
            name='courts_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportingBuddiesApp.courtdetails'),
        ),
    ]
