# Generated by Django 4.2 on 2024-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdatas',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentdatas',
            name='payment_status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentdatas',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
