# Generated by Django 5.0.3 on 2024-04-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
        ('SportingBuddiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='coach_data_ids',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportingBuddiesApp.coaches'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='ground_provider_ids',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportingBuddiesApp.groundproviders'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='SportingBuddiesApp.players'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='player_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='SportingBuddiesApp.players'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='player_3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to='SportingBuddiesApp.players'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='player_data_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_id', to='SportingBuddiesApp.players'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportingBuddiesApp.profiles'),
        ),
        migrations.AddField(
            model_name='paymentdatas',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.bookings'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='coach_data_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SportingBuddiesApp.coaches'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='players_data_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SportingBuddiesApp.players'),
        ),
    ]
