# Generated by Django 5.0.3 on 2024-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportingBuddiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatas',
            name='confirm_password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
