# Generated by Django 5.0.3 on 2024-04-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportingBuddiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='profile_data_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='SportingBuddiesApp.profiles'),
        ),
        migrations.AlterField(
            model_name='coaches',
            name='coaches_profile_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='SportingBuddiesApp.profiles'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_profile_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='SportingBuddiesApp.profiles'),
        ),
    ]
